name: CI/CD Pipeline for Streamlit App on Windows

# This workflow will run on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Use the latest version of Windows Server as the environment
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your desired Python version

      # Step 3: Install necessary dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     

      # Step 5: Deploy the app to Streamlit Cloud (or a server)
      - name: Deploy Streamlit App
        run: |
          streamlit run app.py
